version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: blog_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: blog_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - blog_network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: blog_app
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/blog_db
      NODE_ENV: development
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - blog_network
    command: sh -c "npx prisma migrate deploy && npm run start:dev"

networks:
  blog_network:
    driver: bridge

volumes:
  postgres_data: 